#!/usr/bin/env bash
# Initializing an hour counter
hour=0

#while loop displaying hours from 0 to 12
while [ $hour -le 12 ]
do
    echo "Hour: $hour"

    # Initializing a minute counter
    minute=1

    #nested while loop displaying minutes from 1 to 59
    while [ $minute -le 59 ]
    do
        echo $minute
        ((minute++))
    done

    ((hour++))
done
